// <auto-generated />
using System;
using LAB05_TINTAMILER.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LAB05_TINTAMILER.Migrations
{
    [DbContext(typeof(ConsultoriaDbContext))]
    [Migration("20260914194448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecharegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razonsocial");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId")
                        .HasName("clientes_pkey");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.ComunicacionCliente", b =>
                {
                    b.Property<int>("ComunicacionClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comunicacionclienteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComunicacionClienteId"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("asunto");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("FechaComunicacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechacomunicacion");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("registradopor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("ComunicacionClienteId")
                        .HasName("comunicacionescliente_pkey");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("comunicacionescliente", (string)null);
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empleadoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cargo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.HasKey("EmpleadoId")
                        .HasName("empleados_pkey");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.HitoProyecto", b =>
                {
                    b.Property<int>("HitoProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hitoproyectoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HitoProyectoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaCumplimiento")
                        .HasColumnType("date")
                        .HasColumnName("fechacumplimiento");

                    b.Property<DateOnly>("FechaPlanificada")
                        .HasColumnType("date")
                        .HasColumnName("fechaplanificada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    b.HasKey("HitoProyectoId")
                        .HasName("hitosproyecto_pkey");

                    b.HasIndex("ProyectoId");

                    b.ToTable("hitosproyecto", (string)null);
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.InformeProgreso", b =>
                {
                    b.Property<int>("InformeProgresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("informeprogresoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InformeProgresoId"));

                    b.Property<int>("AvanceGeneral")
                        .HasColumnType("integer")
                        .HasColumnName("avancegeneral");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleadoid");

                    b.Property<DateOnly>("FechaInforme")
                        .HasColumnType("date")
                        .HasColumnName("fechainforme");

                    b.Property<string>("HitosAlcanzados")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hitosalcanzados");

                    b.Property<string>("Pendientes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("pendientes");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    b.Property<string>("Riesgos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("riesgos");

                    b.HasKey("InformeProgresoId")
                        .HasName("informesprogreso_pkey");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("informesprogreso", null, t =>
                        {
                            t.HasCheckConstraint("ck_informes_avance", "avancegeneral >= 0 AND avancegeneral <= 100");
                        });
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.PresupuestoProyecto", b =>
                {
                    b.Property<int>("PresupuestoProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("presupuestoproyectoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PresupuestoProyectoId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecharegistro");

                    b.Property<decimal>("GastoReal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("gastoreal");

                    b.Property<decimal>("MontoEstimado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("montoestimado");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    b.HasKey("PresupuestoProyectoId")
                        .HasName("presupuestosproyecto_pkey");

                    b.HasIndex("ProyectoId");

                    b.ToTable("presupuestosproyecto", null, t =>
                        {
                            t.HasCheckConstraint("ck_presupuesto_estimado", "montoestimado >= 0");

                            t.HasCheckConstraint("ck_presupuesto_gasto", "gastoreal >= 0");
                        });
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProyectoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Planificado")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fechafin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechainicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Objetivos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("objetivos");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("responsableid");

                    b.HasKey("ProyectoId")
                        .HasName("proyectos_pkey");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.TareaProyecto", b =>
                {
                    b.Property<int>("TareaProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tareaproyectoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TareaProyectoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleadoid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaLimite")
                        .HasColumnType("date")
                        .HasColumnName("fechalimite");

                    b.Property<int>("PorcentajeAvance")
                        .HasColumnType("integer")
                        .HasColumnName("porcentajeavance");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyectoid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("TareaProyectoId")
                        .HasName("tareasproyecto_pkey");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("tareasproyecto", null, t =>
                        {
                            t.HasCheckConstraint("ck_tareas_avance", "porcentajeavance >= 0 AND porcentajeavance <= 100");
                        });
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.ComunicacionCliente", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Cliente", "Cliente")
                        .WithMany("Comunicaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comunicaciones_clientes");

                    b.HasOne("LAB05_TINTAMILER.Models.Proyecto", "Proyecto")
                        .WithMany("Comunicaciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comunicaciones_proyectos");

                    b.Navigation("Cliente");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.HitoProyecto", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Proyecto", "Proyecto")
                        .WithMany("Hitos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hitos_proyectos");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.InformeProgreso", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Empleado", "Empleado")
                        .WithMany("InformesEmitidos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_informes_empleados");

                    b.HasOne("LAB05_TINTAMILER.Models.Proyecto", "Proyecto")
                        .WithMany("Informes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_informes_proyectos");

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.PresupuestoProyecto", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Proyecto", "Proyecto")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presupuestos_proyectos");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Proyecto", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Cliente", "Cliente")
                        .WithMany("Proyectos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proyectos_clientes");

                    b.HasOne("LAB05_TINTAMILER.Models.Empleado", "Responsable")
                        .WithMany("ProyectosResponsables")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proyectos_empleados");

                    b.Navigation("Cliente");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.TareaProyecto", b =>
                {
                    b.HasOne("LAB05_TINTAMILER.Models.Empleado", "Empleado")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tareas_empleados");

                    b.HasOne("LAB05_TINTAMILER.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tareas_proyectos");

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Cliente", b =>
                {
                    b.Navigation("Comunicaciones");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Empleado", b =>
                {
                    b.Navigation("InformesEmitidos");

                    b.Navigation("ProyectosResponsables");

                    b.Navigation("TareasAsignadas");
                });

            modelBuilder.Entity("LAB05_TINTAMILER.Models.Proyecto", b =>
                {
                    b.Navigation("Comunicaciones");

                    b.Navigation("Hitos");

                    b.Navigation("Informes");

                    b.Navigation("Presupuestos");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
